vars:
- package: re_nobm_pcc
stages:
  simulate:
    cmd: python -m ${package}.simulate
    deps:
    - data/oasim_param
    - data/nobm
    outs:
    - data/oasim
    frozen: true
  preprocess:
    cmd: python -m ${package}.preprocess
    deps:
    - data/nobm
    - data/oasim
    outs:
    - data/labelled.zarr
    frozen: false
  learn:
    cmd: python -m ${package}.learn
    deps:
    - ${package}/learn.py
    - data/labelled.zarr
    outs:
    - data/fit.zarr
    - data/model.keras
    - data/checkpoint
  evaluate:
    cmd: python -m ${package}.evaluate
    deps:
    - data/fit.zarr
    - data/model.keras
    metrics:
    - data/metrics.json
