vars:
- package: re_nobm_pcc
stages:
  simulate:
    cmd: python -m ${package}.simulate
    deps:
    - data/oasim_param
    - data/nobm
    outs:
    - data/oasim
  preprocess:
    cmd: python -m ${package}.preprocess
    deps:
    - data/oasim
    outs:
    - data/labelled.zarr
  learn:
    cmd: >
      srun
      --job-name=${package}.learn
      --output="logs/slurm-%x-%j.out"
      --cpus-per-task=6
      --mem-per-cpu=25600M
      --exclude=poseidon-compute-13
      task python -O -m ${package}.learn
#      --gres=gpu:2
    deps:
    - data/rrs_day_tfds
    outs:
    - data/fit
    - data/fit.npz
    - data/network
    metrics:
    - data/metrics.json
