stages:
  perceptron:
    cmd: python -m re_nobm_pcc.perceptron
    deps:
    - data
    - re_nobm_pcc/kit.py
    - re_nobm_pcc/perceptron.py
    - re_nobm_pcc/preprocessing.py
    outs:
    - models/logs/perceptron
