stages:
  notebooks:
    foreach:
    - preview
    do:
      cmd: >
        jupyter nbconvert
        --execute
        --ExecutePreprocessor.kernel_name=re-nobm-pcc
        --to=html
        --output-dir=docs
        notebooks/${item}.ipynb
      outs:
      - docs/${item}.html
  simulate: # FIXME oasim compilation by skbuild is borked
    cmd:
    - mkdir data/rrs_day
    - >
      srun
      --job-name=re_nobm_pcc.simulate
      --output="logs/slurm-%x-$j-%3t.out"
      --ntasks=288
      --mem-per-cpu=20480M
      --exclude=poseidon-compute-13
      task python -O -m re_nobm_pcc.simulate
    deps:
    - data/nobm_day
    - data/oasim_param
    outs:
    - data/rrs_day
  preprocess:
    cmd: >
      srun
      --job-name=re_nobm_pcc.preprocess
      --output="logs/slurm-%x-%j.out"
      --exclude=poseidon-compute-13
      task python -O -m re_nobm_pcc.simulate
    deps:
    - data/rrs_day
    outs:
    - data/rrs_day_tfds
  learn:
    cmd: >
      srun
      --job-name=re_nobm_pcc.learn
      --output="${project-dir}/logs/slurm-%x-%j.out"
      --cpus-per-task=6
      --mem-per-cpu=25600M
      --exclude=poseidon-compute-13
      task python -O -m re_nobm_pcc.learn
#      --gres=gpu:2
    params:
    - project-dir
    deps:
    - data/rrs_day_tfds
    outs:
    - data/fit
    - data/fit.npz
    - data/network
    metrics:
    - data/metrics.json:
        cache: false
