[tool.poetry]
name = "RE-NOBM-PCC"
version = "0.1.0"
description = ""
authors = ["Ian Carroll <ian.t.carroll@nasa.gov>"]

[tool.poetry.dependencies]
python = "^3.8,<3.11"
scipy = "^1.8.1"
tensorflow = "^2.8.0"
xarray = {extras = ["parallel"], version = "^2022.6.0"}
# pip install --no-binary netCDF4 netCDF4
hvplot = "^0.8.1"

[tool.poetry.dev-dependencies]
dvc = {version = "^2.9.5", extras = ["gdrive"]}
jupyterlab = "^3.2.9"
pytest = "^7.0.1"
