[tool.poetry]
name = "RE-NOBM-PCC"
version = "0.1.0"
description = ""
authors = ["Ian Carroll <ian.t.carroll@nasa.gov>"]

[tool.poetry.dependencies]
dask = "^2022.2.0"
netCDF4 = "^1.5.8"
python = ">=3.8, <3.11"
tensorflow = "^2.8.0"
xarray = "^0.21.1"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.2.9"
hvplot = "^0.7.3"
pytest = "^7.0.1"
pylint = "^2.12.2"
dvc = {version = "^2.9.5", extras = ["gdrive"]}
